enum WithdrawStatus {
	REGISTERED = 0,
	CONFIRMED_BY_USER = 11,
	CHECKED_BY_SYS_FAILED_WAIT_FOR_ADMIN = 21,
	CHECKED_BY_SYS_READY_TO_EXECUTE = 23,
	CONFIRMED_BY_ADMIN_READY_TO_EXECUTE = 27,
	EXECUTING = 31,
	EXEC_PENDING = 33,
	EXEC_FAILED_RETRY_IN_5_MINUTES = 37,
	EXEC_HOLD = 39,
	REJECTED_BY_SYS = 41,
	REJECTED_BY_ADMIN = 43,
	FULFILLED = 91,
}

enum WithdrawType {
	TRANSFER_TO_OUTSIDE = 11,
	TRANSFER_TO_ANOTHER_USER = 21,
}

export {
	WithdrawStatus,
	WithdrawType,
};
